### ISSUE TITLE
Hour parametresi çalışmıyor

### ISSUE THREAD

**Issue by siriiuss** [emirkabal/deprem-api#7]
Hour parametresi çalışmıyor. Hata mesajıda göstermiyor.

Python=3.10
autopep8=2.0.2
beautifulsoup4=4.11.2
flask=2.2.3
gunicorn=20.1.0
schedule=1.1.0
![image](https://user-images.githubusercontent.com/66683435/225555116-ad0e3725-dfb7-439d-86bd-c976063f0180.png)

**Comment by emirkabal** [comment]
Gün içerisinde bakacağım

**Comment by siriiuss** [comment]
> Gün içerisinde bakacağım

Hocam pull request kontrol eder misiniz. Hatayı düzelttim.
