### ISSUE TITLE
filtreler hakkında

### ISSUE THREAD

**Issue by alperians** [emirkabal/deprem-api#9]
Merhaba 
filtreler den "Size" sadece integer/tamsayı değerler için şu an aktif çalışabiliyor. noktalı virgüllü değerlerde çalışmıyor. 
"hour" filtresi işlev görmüyor.
kolay gelsin iyi çalışmalar.

**Comment by emirkabal** [comment]
Sorun https://github.com/emirkabal/deprem-api/commit/92a0f9ca692687c932250c7ac7cd94065e50c3fd ile birlikte çözülmüştür.
